default_language_version:
  python: python3.7
default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        name: Check for trailing whitespaces
      - id: check-yaml
        name: Check YAML files
      - id: detect-private-key
        name: Detect private keys
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -  id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        args:
          - -m=3
        name: Sort imports with isort
