default_language_version:
  python: python3.7
default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: detect-aws-credentials
        name: Detect AWS secrets
      - id: detect-private-key
        name: Detect private keys
      - id: no-commit-to-branch
        args:
          - --branch=master
        name: Don't commit to master
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        args:
          - -m=3
        name: Sort imports with isort
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    sha: v1.0.0
    hooks:
      - id: rst-linter
