default_language_version:
  python: python3.8
default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        name: Check for trailing whitespaces
      - id: check-yaml
        name: Check YAML files
      - id: detect-private-key
        name: Detect private keys
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        name: Format code with Black
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        name: Sort imports with isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        name: Lint code with flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        name: my[py] static type check
        args:
          - --ignore-missing-imports
