matrix:
  include:
    - language: elm
      elm: elm0.19.1
      script:
        - cd elm
        - chmod +x run_tests.sh
        - "./run_tests"
    - language: bash
      sudo: true
      before_install:
        - sudo add-apt-repository ppa:duggan/bats --yes
        - sudo apt-get update -qq
        - sudo apt-get install -qq bats
      script:
        - cd bash
        - chmod +x run_tests.sh
        - "./run_tests.sh"
    - language: python
      python: 3.6
      script:
          - cd python
          - pip install -r requirements.txt
          - coverage run -m pytest
          - coverage report -m
          - coverage xml
          - python-codacy-coverage -r coverage.xml
    - language: scala
      scala: 2.12.1
      script:
          - cd scala
          - chmod +x run_tests.sh
          - "./run_tests.sh"
    - language: haskell
      sudo: false
      # Caching so the next build will be fast too.
      cache:
        directories:
        - $HOME/.stack
      before_install:
      # Download and unpack the stack executable
          - mkdir -p ~/.local/bin
          - export PATH=$HOME/.local/bin:$PATH
          - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      # Configure stack to use the system GHC installation
          - stack config set system-ghc --global true
          - export PATH=/opt/ghc/7.10.2/bin:$PATH
      install: true
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-7.10.2

      script:
          - cd haskell
          - chmod +x run_tests.sh
          - "./run_tests.sh"
