matrix:
  include:
    - language: python
      python: 3.6
      script:
          - cd python
          - pytest 
    - language: scala
      scala: 2.12.1
      script:
          - cd scala
          - "./run_test.sh"
