
matrix:
  include:
    -language: python
     python: 3.6
     script:
         - cd python
         - pytest 
    -language: scala
     scala: 2.12
     script:
         - cd scala
         - for i in $( ls); do  cd $i; sbt ++$TRAVIS_SCALA_VERSION test; cd ..  ; done 
